{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "6146d77b-e07a-4780-b741-ec518ccac3fa",
   "metadata": {},
   "source": [
    "## Extraemos la información en la carpeta donde se esté ejecutando el código"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "25bc3e0f-2b6b-4dab-8f80-90bc18a2db16",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dataset guardado en: C:\\Users\\richa\\Modulo4\n"
     ]
    }
   ],
   "source": [
    "#!pip install sqlalchemy psycopg2-binary pandas openpyxl\n",
    "#!pip install kagglehub\n",
    "import kagglehub\n",
    "import shutil\n",
    "import os\n",
    "\n",
    "# Descargar dataset\n",
    "path = kagglehub.dataset_download(\"jaredrosas/global-superstore-orders-2016-es-esp\")\n",
    "\n",
    "# Carpeta actual\n",
    "destino = os.getcwd()\n",
    "\n",
    "# Copiar el contenido del dataset a la carpeta actual\n",
    "for archivo in os.listdir(path):\n",
    "    origen = os.path.join(path, archivo)\n",
    "    destino_archivo = os.path.join(destino, archivo)\n",
    "\n",
    "    if os.path.isfile(origen):\n",
    "        shutil.copy2(origen, destino_archivo)\n",
    "    elif os.path.isdir(origen):\n",
    "        shutil.copytree(origen, destino_archivo, dirs_exist_ok=True)\n",
    "\n",
    "print(\"Dataset guardado en:\", destino)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e94824ee-2de9-420e-9f4f-da85c2045e23",
   "metadata": {},
   "source": [
    "## Cargamos el archivo y lo transformamos al modelo estrella"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "da08ed28-76b5-4cec-a765-e509729ee6ba",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Modelo estrella generado correctamente.\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "# ==========================================\n",
    "# CARGAR ARCHIVO\n",
    "# ==========================================\n",
    "\n",
    "archivo = \"Global Superstore Orders 2016_es-ES.xlsx\"\n",
    "\n",
    "pedidos = pd.read_excel(archivo, sheet_name=\"Pedidos\")\n",
    "personas = pd.read_excel(archivo, sheet_name=\"Personas\")\n",
    "\n",
    "# ==========================================\n",
    "# LIMPIEZA DE FECHAS\n",
    "# ==========================================\n",
    "\n",
    "pedidos[\"Fecha de pedido\"] = pd.to_datetime(\n",
    "    pedidos[\"Fecha de pedido\"],\n",
    "    dayfirst=True\n",
    ").dt.date\n",
    "\n",
    "pedidos[\"Fecha de envío\"] = pd.to_datetime(\n",
    "    pedidos[\"Fecha de envío\"],\n",
    "    dayfirst=True\n",
    ").dt.date\n",
    "\n",
    "# ==========================================\n",
    "# CREAMOS LAS DIMENSIONES DEL MODELO ESTRELLA\n",
    "# ==========================================\n",
    "\n",
    "# ==========================================\n",
    "# DIM_CLIENTE\n",
    "# ==========================================\n",
    "\n",
    "DIM_CLIENTE = pedidos[\n",
    "    [\n",
    "        \"ID de cliente\",\n",
    "        \"Nombre de cliente\",\n",
    "        \"Segmento\"\n",
    "    ]\n",
    "].drop_duplicates()\n",
    "\n",
    "# ==========================================\n",
    "# DIM_PRODUCTO\n",
    "# ==========================================\n",
    "\n",
    "DIM_PRODUCTO = pedidos[\n",
    "    [\n",
    "        \"ID de producto\",\n",
    "        \"Categoría\",\n",
    "        \"Subcategoría\",\n",
    "        \"Nombre de producto\"\n",
    "    ]\n",
    "].drop_duplicates()\n",
    "\n",
    "# ==========================================\n",
    "# DIM_GEOGRAFIA\n",
    "# ==========================================\n",
    "\n",
    "DIM_GEOGRAFIA = (\n",
    "    pedidos[\n",
    "        [\n",
    "            \"Código postal\",\n",
    "            \"Ciudad\",\n",
    "            \"Estado\",\n",
    "            \"País\",\n",
    "            \"Región\",\n",
    "            \"Mercado\"\n",
    "        ]\n",
    "    ]\n",
    "    .drop_duplicates()\n",
    "    .reset_index(drop=True)\n",
    ")\n",
    "\n",
    "DIM_GEOGRAFIA.insert(\n",
    "    0,\n",
    "    \"id_geografia\",\n",
    "    range(1, len(DIM_GEOGRAFIA) + 1)\n",
    ")\n",
    "\n",
    "# ==========================================\n",
    "# DIM_TIEMPO\n",
    "# ==========================================\n",
    "\n",
    "DIM_TIEMPO = (\n",
    "    pedidos[[\"Fecha de pedido\"]]\n",
    "    .drop_duplicates()\n",
    "    .copy()\n",
    ")\n",
    "\n",
    "DIM_TIEMPO[\"Fecha de pedido\"] = pd.to_datetime(\n",
    "    DIM_TIEMPO[\"Fecha de pedido\"]\n",
    ")\n",
    "\n",
    "DIM_TIEMPO[\"dia\"] = DIM_TIEMPO[\"Fecha de pedido\"].dt.day\n",
    "DIM_TIEMPO[\"mes\"] = DIM_TIEMPO[\"Fecha de pedido\"].dt.month\n",
    "DIM_TIEMPO[\"trimestre\"] = DIM_TIEMPO[\"Fecha de pedido\"].dt.quarter\n",
    "DIM_TIEMPO[\"anio\"] = DIM_TIEMPO[\"Fecha de pedido\"].dt.year\n",
    "\n",
    "# Dejar la fecha sin hora para exportar\n",
    "DIM_TIEMPO[\"Fecha de pedido\"] = DIM_TIEMPO[\"Fecha de pedido\"].dt.date\n",
    "\n",
    "DIM_TIEMPO = DIM_TIEMPO.reset_index(drop=True)\n",
    "\n",
    "DIM_TIEMPO.insert(\n",
    "    0,\n",
    "    \"id_tiempo\",\n",
    "    range(1, len(DIM_TIEMPO) + 1)\n",
    ")\n",
    "\n",
    "# ==========================================\n",
    "# DIM_ENVIO\n",
    "# ==========================================\n",
    "\n",
    "DIM_ENVIO = (\n",
    "    pedidos[\n",
    "        [\n",
    "            \"Fecha de envío\",\n",
    "            \"Modo de envío\",\n",
    "            \"Prioridad de pedido\"\n",
    "        ]\n",
    "    ]\n",
    "    .drop_duplicates()\n",
    "    .reset_index(drop=True)\n",
    ")\n",
    "\n",
    "DIM_ENVIO.insert(\n",
    "    0,\n",
    "    \"id_envio\",\n",
    "    range(1, len(DIM_ENVIO) + 1)\n",
    ")\n",
    "\n",
    "# ==========================================\n",
    "# DIM_PERSONA\n",
    "# ==========================================\n",
    "\n",
    "DIM_PERSONA = personas.drop_duplicates().reset_index(drop=True)\n",
    "\n",
    "DIM_PERSONA.insert(\n",
    "    0,\n",
    "    \"id_persona\",\n",
    "    range(1, len(DIM_PERSONA) + 1)\n",
    ")\n",
    "\n",
    "# ==========================================\n",
    "# AGREGAR FKs A PEDIDOS\n",
    "# ==========================================\n",
    "\n",
    "fact = pedidos.copy()\n",
    "\n",
    "# ----- GEOGRAFIA -----\n",
    "\n",
    "fact = fact.merge(\n",
    "    DIM_GEOGRAFIA,\n",
    "    how=\"left\",\n",
    "    on=[\n",
    "        \"Código postal\",\n",
    "        \"Ciudad\",\n",
    "        \"Estado\",\n",
    "        \"País\",\n",
    "        \"Región\",\n",
    "        \"Mercado\"\n",
    "    ]\n",
    ")\n",
    "\n",
    "# ----- TIEMPO -----\n",
    "\n",
    "fact = fact.merge(\n",
    "    DIM_TIEMPO[\n",
    "        [\n",
    "            \"id_tiempo\",\n",
    "            \"Fecha de pedido\"\n",
    "        ]\n",
    "    ],\n",
    "    how=\"left\",\n",
    "    on=\"Fecha de pedido\"\n",
    ")\n",
    "\n",
    "# ----- ENVIO -----\n",
    "\n",
    "fact = fact.merge(\n",
    "    DIM_ENVIO,\n",
    "    how=\"left\",\n",
    "    on=[\n",
    "        \"Fecha de envío\",\n",
    "        \"Modo de envío\",\n",
    "        \"Prioridad de pedido\"\n",
    "    ]\n",
    ")\n",
    "\n",
    "# ----- PERSONA -----\n",
    "\n",
    "fact = fact.merge(\n",
    "    DIM_PERSONA[\n",
    "        [\n",
    "            \"id_persona\",\n",
    "            \"Región\"\n",
    "        ]\n",
    "    ],\n",
    "    how=\"left\",\n",
    "    on=\"Región\"\n",
    ")\n",
    "\n",
    "# ==========================================\n",
    "# FACT_VENTAS\n",
    "# ==========================================\n",
    "\n",
    "FACT_VENTAS = fact[\n",
    "    [\n",
    "        \"ID de fila\",\n",
    "        \"ID de pedido\",\n",
    "        \"ID de cliente\",\n",
    "        \"ID de producto\",\n",
    "        \"id_geografia\",\n",
    "        \"id_tiempo\",\n",
    "        \"id_envio\",\n",
    "        \"id_persona\",\n",
    "        \"Ventas\",\n",
    "        \"Cantidad\",\n",
    "        \"Descuento\",\n",
    "        \"Beneficio\",\n",
    "        \"Costo de envío\"\n",
    "    ]\n",
    "]\n",
    "\n",
    "# ==========================================\n",
    "# EXPORTAR A EXCEL\n",
    "# ==========================================\n",
    "\n",
    "with pd.ExcelWriter(\n",
    "    \"Modelo_Estrella_Global_Superstore.xlsx\",\n",
    "    date_format=\"dd/mm/yyyy\",\n",
    "    datetime_format=\"dd/mm/yyyy\"\n",
    ") as writer:\n",
    "\n",
    "    DIM_CLIENTE.to_excel(writer, sheet_name=\"DIM_CLIENTE\", index=False)\n",
    "    DIM_PRODUCTO.to_excel(writer, sheet_name=\"DIM_PRODUCTO\", index=False)\n",
    "    DIM_GEOGRAFIA.to_excel(writer, sheet_name=\"DIM_GEOGRAFIA\", index=False)\n",
    "    DIM_TIEMPO.to_excel(writer, sheet_name=\"DIM_TIEMPO\", index=False)\n",
    "    DIM_ENVIO.to_excel(writer, sheet_name=\"DIM_ENVIO\", index=False)\n",
    "    DIM_PERSONA.to_excel(writer, sheet_name=\"DIM_PERSONA\", index=False)\n",
    "    FACT_VENTAS.to_excel(writer, sheet_name=\"FACT_VENTAS\", index=False)\n",
    "\n",
    "print(\"Modelo estrella generado correctamente.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "70ad88f0-c6e5-48ee-b0a9-b3bc432fa346",
   "metadata": {},
   "source": [
    "## TEST DE VALIDACIÓN DEL MODELO ESTRELLA"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "6f3c4b7b-37bf-4cfe-b9a5-5aba2391f82a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================================================\n",
      "VALIDACIÓN DEL MODELO ESTRELLA\n",
      "============================================================\n",
      "\n",
      "1. Registros\n",
      "Pedidos originales : 51290\n",
      "FACT_VENTAS        : 51290\n",
      "✓ Correcto\n",
      "\n",
      "2. Claves primarias\n",
      "✓ DIM_GEOGRAFIA: id_geografia es única\n",
      "✓ DIM_TIEMPO: id_tiempo es única\n",
      "✓ DIM_ENVIO: id_envio es única\n",
      "✓ DIM_PERSONA: id_persona es única\n",
      "\n",
      "3. Duplicados en dimensiones\n",
      "DIM_CLIENTE  : 0\n",
      "DIM_PRODUCTO : 0\n",
      "DIM_GEOGRAFIA: 0\n",
      "DIM_TIEMPO   : 0\n",
      "DIM_ENVIO    : 0\n",
      "DIM_PERSONA  : 0\n",
      "\n",
      "4. Llaves foráneas nulas\n",
      "id_geografia      0\n",
      "id_tiempo         0\n",
      "id_envio          0\n",
      "id_persona      384\n",
      "dtype: int64\n",
      "\n",
      "5. Integridad referencial\n",
      "Clientes: True\n",
      "Productos: True\n",
      "Geografía: True\n",
      "Tiempo: True\n",
      "Envío: True\n",
      "Persona: False\n",
      "\n",
      "6. Validación de medidas\n",
      "✓ Ventas: OK (12642501.90988)\n",
      "✓ Cantidad: OK (178312)\n",
      "✓ Descuento: OK (7329.727999999999)\n",
      "✓ Beneficio: OK (1467457.2912799998)\n",
      "✓ Costo de envío: OK (1358085.7033999995)\n",
      "\n",
      "============================================================\n",
      "VALIDACIÓN FINALIZADA\n",
      "============================================================\n"
     ]
    }
   ],
   "source": [
    "print(\"=\" * 60)\n",
    "print(\"VALIDACIÓN DEL MODELO ESTRELLA\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "# 1. Número de registros\n",
    "print(\"\\n1. Registros\")\n",
    "print(f\"Pedidos originales : {len(pedidos)}\")\n",
    "print(f\"FACT_VENTAS        : {len(FACT_VENTAS)}\")\n",
    "print(\"✓ Correcto\" if len(pedidos) == len(FACT_VENTAS) else \"✗ Error\")\n",
    "\n",
    "# 2. Claves primarias únicas\n",
    "print(\"\\n2. Claves primarias\")\n",
    "\n",
    "dimensiones = {\n",
    "    \"DIM_GEOGRAFIA\": (\"id_geografia\", DIM_GEOGRAFIA),\n",
    "    \"DIM_TIEMPO\": (\"id_tiempo\", DIM_TIEMPO),\n",
    "    \"DIM_ENVIO\": (\"id_envio\", DIM_ENVIO),\n",
    "    \"DIM_PERSONA\": (\"id_persona\", DIM_PERSONA)\n",
    "}\n",
    "\n",
    "for nombre, (pk, df) in dimensiones.items():\n",
    "    if df[pk].is_unique:\n",
    "        print(f\"✓ {nombre}: {pk} es única\")\n",
    "    else:\n",
    "        print(f\"✗ {nombre}: {pk} tiene duplicados\")\n",
    "\n",
    "# 3. Duplicados en dimensiones\n",
    "print(\"\\n3. Duplicados en dimensiones\")\n",
    "\n",
    "print(f\"DIM_CLIENTE  : {DIM_CLIENTE.duplicated().sum()}\")\n",
    "print(f\"DIM_PRODUCTO : {DIM_PRODUCTO.duplicated().sum()}\")\n",
    "print(f\"DIM_GEOGRAFIA: {DIM_GEOGRAFIA.duplicated().sum()}\")\n",
    "print(f\"DIM_TIEMPO   : {DIM_TIEMPO.duplicated().sum()}\")\n",
    "print(f\"DIM_ENVIO    : {DIM_ENVIO.duplicated().sum()}\")\n",
    "print(f\"DIM_PERSONA  : {DIM_PERSONA.duplicated().sum()}\")\n",
    "\n",
    "# 4. Llaves foráneas nulas\n",
    "print(\"\\n4. Llaves foráneas nulas\")\n",
    "\n",
    "fks = [\n",
    "    \"id_geografia\",\n",
    "    \"id_tiempo\",\n",
    "    \"id_envio\",\n",
    "    \"id_persona\"\n",
    "]\n",
    "\n",
    "print(FACT_VENTAS[fks].isnull().sum())\n",
    "\n",
    "# 5. Integridad referencial\n",
    "print(\"\\n5. Integridad referencial\")\n",
    "\n",
    "print(\n",
    "    \"Clientes:\",\n",
    "    FACT_VENTAS[\"ID de cliente\"].isin(DIM_CLIENTE[\"ID de cliente\"]).all()\n",
    ")\n",
    "\n",
    "print(\n",
    "    \"Productos:\",\n",
    "    FACT_VENTAS[\"ID de producto\"].isin(DIM_PRODUCTO[\"ID de producto\"]).all()\n",
    ")\n",
    "\n",
    "print(\n",
    "    \"Geografía:\",\n",
    "    FACT_VENTAS[\"id_geografia\"].isin(DIM_GEOGRAFIA[\"id_geografia\"]).all()\n",
    ")\n",
    "\n",
    "print(\n",
    "    \"Tiempo:\",\n",
    "    FACT_VENTAS[\"id_tiempo\"].isin(DIM_TIEMPO[\"id_tiempo\"]).all()\n",
    ")\n",
    "\n",
    "print(\n",
    "    \"Envío:\",\n",
    "    FACT_VENTAS[\"id_envio\"].isin(DIM_ENVIO[\"id_envio\"]).all()\n",
    ")\n",
    "\n",
    "print(\n",
    "    \"Persona:\",\n",
    "    FACT_VENTAS[\"id_persona\"].isin(DIM_PERSONA[\"id_persona\"]).all()\n",
    ")\n",
    "\n",
    "# 6. Totales de medidas\n",
    "print(\"\\n6. Validación de medidas\")\n",
    "\n",
    "medidas = [\n",
    "    \"Ventas\",\n",
    "    \"Cantidad\",\n",
    "    \"Descuento\",\n",
    "    \"Beneficio\",\n",
    "    \"Costo de envío\"\n",
    "]\n",
    "\n",
    "for medida in medidas:\n",
    "    original = pedidos[medida].sum()\n",
    "    fact = FACT_VENTAS[medida].sum()\n",
    "\n",
    "    if original == fact:\n",
    "        print(f\"✓ {medida}: OK ({original})\")\n",
    "    else:\n",
    "        print(f\"✗ {medida}: Original={original} Fact={fact}\")\n",
    "\n",
    "print(\"\\n\" + \"=\" * 60)\n",
    "print(\"VALIDACIÓN FINALIZADA\")\n",
    "print(\"=\" * 60)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "69b2c563-2b1f-4f5d-beb1-f6fac09757d8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'Canadá'}\n"
     ]
    }
   ],
   "source": [
    "regiones_faltantes = set(pedidos[\"Región\"]) - set(personas[\"Región\"])\n",
    "\n",
    "print(regiones_faltantes)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a49f1447-6d32-47e1-b8d3-23c8856159cd",
   "metadata": {},
   "source": [
    "# Conexión con AWS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "0b34f425-bb56-47e6-9c39-184c6e92e081",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Conexión exitosa\n",
      "PostgreSQL 17.7 on x86_64-pc-linux-gnu, compiled by x86_64-pc-linux-gnu-gcc (GCC) 10.5.0, 64-bit\n"
     ]
    }
   ],
   "source": [
    "from sqlalchemy import create_engine, text\n",
    "\n",
    "# =====================================\n",
    "# CONFIGURACIÓN AURORA\n",
    "# =====================================\n",
    "\n",
    "AURORA_HOST = \"aurora-mod4.cluster-cr9wjf4zhb8s.us-east-1.rds.amazonaws.com\"\n",
    "AURORA_PASSWORD = \"ModuloDiplomado4\"\n",
    "AURORA_DATABASE = \"ecomerce\"\n",
    "\n",
    "# =====================================\n",
    "# CREAR ENGINE\n",
    "# =====================================\n",
    "\n",
    "engine = create_engine(\n",
    "    f\"postgresql+psycopg2://postgres:{AURORA_PASSWORD}@{AURORA_HOST}:5432/{AURORA_DATABASE}\"\n",
    ")\n",
    "\n",
    "# =====================================\n",
    "# PRUEBA DE CONEXIÓN\n",
    "# =====================================\n",
    "\n",
    "try:\n",
    "    with engine.connect() as conn:\n",
    "        version = conn.execute(\n",
    "            text(\"SELECT version();\")\n",
    "        ).scalar()\n",
    "\n",
    "    print(\"✅ Conexión exitosa\")\n",
    "    print(version)\n",
    "\n",
    "except Exception as e:\n",
    "    print(\"❌ Error de conexión\")\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "8a2798d0-2e52-4ce9-9012-3b5b7171e1c6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Schema ecomerce_dwh creado correctamente\n"
     ]
    }
   ],
   "source": [
    "SCHEMA = \"ecomerce_dwh\"\n",
    "\n",
    "with engine.begin() as conn:\n",
    "    conn.execute(\n",
    "        text(f\"CREATE SCHEMA IF NOT EXISTS {SCHEMA}\")\n",
    "    )\n",
    "\n",
    "print(f\"✅ Schema {SCHEMA} creado correctamente\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "15b6bbb3-ecf4-49bc-bedc-aa28d90d0353",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ dim_cliente       17,415 filas cargadas\n",
      "✅ dim_producto       3,788 filas cargadas\n",
      "✅ dim_geografia      3,856 filas cargadas\n",
      "✅ dim_tiempo         1,430 filas cargadas\n",
      "✅ dim_envio          9,471 filas cargadas\n",
      "✅ dim_persona           24 filas cargadas\n",
      "✅ fact_ventas       51,290 filas cargadas\n",
      "\n",
      "✅ Carga completa en PostgreSQL.\n",
      "\n",
      "========== VALIDACIÓN ==========\n",
      "\n",
      "dim_cliente    : 17,415 filas\n",
      "dim_producto   : 3,788 filas\n",
      "dim_geografia  : 3,856 filas\n",
      "dim_tiempo     : 1,430 filas\n",
      "dim_envio      : 9,471 filas\n",
      "dim_persona    : 24 filas\n",
      "fact_ventas    : 51,290 filas\n",
      "\n",
      "✅ Validación finalizada.\n"
     ]
    }
   ],
   "source": [
    "from sqlalchemy import text\n",
    "\n",
    "# ==========================================\n",
    "# DICCIONARIO DE TABLAS\n",
    "# ==========================================\n",
    "\n",
    "tables = {\n",
    "    \"dim_cliente\": DIM_CLIENTE,\n",
    "    \"dim_producto\": DIM_PRODUCTO,\n",
    "    \"dim_geografia\": DIM_GEOGRAFIA,\n",
    "    \"dim_tiempo\": DIM_TIEMPO,\n",
    "    \"dim_envio\": DIM_ENVIO,\n",
    "    \"dim_persona\": DIM_PERSONA,\n",
    "    \"fact_ventas\": FACT_VENTAS\n",
    "}\n",
    "\n",
    "# ==========================================\n",
    "# CARGAR TABLAS A POSTGRESQL\n",
    "# ==========================================\n",
    "\n",
    "def load_data(tables: dict, engine, schema: str = \"ecomerce_dwh\"):\n",
    "\n",
    "    tablas_en_orden = [\n",
    "        \"dim_cliente\",\n",
    "        \"dim_producto\",\n",
    "        \"dim_geografia\",\n",
    "        \"dim_tiempo\",\n",
    "        \"dim_envio\",\n",
    "        \"dim_persona\",\n",
    "        \"fact_ventas\"\n",
    "    ]\n",
    "\n",
    "    for nombre in tablas_en_orden:\n",
    "\n",
    "        tables[nombre].to_sql(\n",
    "            name=nombre,\n",
    "            con=engine,\n",
    "            schema=schema,\n",
    "            if_exists=\"replace\",\n",
    "            index=False,\n",
    "            chunksize=1000,\n",
    "            method=\"multi\"\n",
    "        )\n",
    "\n",
    "        print(f\"✅ {nombre:15s} {len(tables[nombre]):>8,} filas cargadas\")\n",
    "\n",
    "    print(\"\\n✅ Carga completa en PostgreSQL.\")\n",
    "\n",
    "# ==========================================\n",
    "# EJECUTAR CARGA\n",
    "# ==========================================\n",
    "\n",
    "load_data(tables, engine, schema=SCHEMA)\n",
    "\n",
    "# ==========================================\n",
    "# VALIDAR CANTIDAD DE REGISTROS\n",
    "# ==========================================\n",
    "\n",
    "print(\"\\n========== VALIDACIÓN ==========\\n\")\n",
    "\n",
    "with engine.connect() as conn:\n",
    "\n",
    "    for tabla in tables.keys():\n",
    "\n",
    "        filas = conn.execute(\n",
    "            text(f\"SELECT COUNT(*) FROM {SCHEMA}.{tabla};\")\n",
    "        ).scalar()\n",
    "\n",
    "        print(f\"{tabla:15s}: {filas:,} filas\")\n",
    "\n",
    "print(\"\\n✅ Validación finalizada.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5bddb786-22eb-4f4f-91f3-d442ac21dcef",
   "metadata": {},
   "source": [
    "## Consultas SQL"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8688ad8e-2f97-4938-95f3-390e1c108b43",
   "metadata": {},
   "source": [
    "### 1. CTE + Ranking simple, ¿Qué productos generan la mayor rentabilidad?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "c3d2285b-7658-42c4-95bb-c80ced2d402a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>producto</th>\n",
       "      <th>beneficio_total</th>\n",
       "      <th>ranking</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Canon imageCLASS 2200 Advanced Copier</td>\n",
       "      <td>25199.9280</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Cisco Smart Phone, Full Size</td>\n",
       "      <td>17238.5206</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Motorola Smart Phone, Full Size</td>\n",
       "      <td>17027.1130</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Hoover Stove, Red</td>\n",
       "      <td>11807.9690</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Sauder Classic Bookcase, Traditional</td>\n",
       "      <td>10672.0730</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Harbour Creations Executive Leather Armchair, ...</td>\n",
       "      <td>10427.3260</td>\n",
       "      <td>6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Nokia Smart Phone, Full Size</td>\n",
       "      <td>9938.1955</td>\n",
       "      <td>7</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Cisco Smart Phone, with Caller ID</td>\n",
       "      <td>9786.6408</td>\n",
       "      <td>8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>Nokia Smart Phone, with Caller ID</td>\n",
       "      <td>9465.3257</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>Belkin Router, USB</td>\n",
       "      <td>8955.0180</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                            producto  beneficio_total  ranking\n",
       "0              Canon imageCLASS 2200 Advanced Copier       25199.9280        1\n",
       "1                       Cisco Smart Phone, Full Size       17238.5206        2\n",
       "2                    Motorola Smart Phone, Full Size       17027.1130        3\n",
       "3                                  Hoover Stove, Red       11807.9690        4\n",
       "4               Sauder Classic Bookcase, Traditional       10672.0730        5\n",
       "5  Harbour Creations Executive Leather Armchair, ...       10427.3260        6\n",
       "6                       Nokia Smart Phone, Full Size        9938.1955        7\n",
       "7                  Cisco Smart Phone, with Caller ID        9786.6408        8\n",
       "8                  Nokia Smart Phone, with Caller ID        9465.3257        9\n",
       "9                                 Belkin Router, USB        8955.0180       10"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "query1 = \"\"\"\n",
    "WITH rentabilidad_producto AS (\n",
    "\n",
    "    SELECT\n",
    "        dp.\"Nombre de producto\" AS producto,\n",
    "        SUM(fv.\"Beneficio\") AS beneficio_total\n",
    "\n",
    "    FROM ecomerce_dwh.fact_ventas fv\n",
    "    JOIN ecomerce_dwh.dim_producto dp\n",
    "        ON fv.\"ID de producto\" = dp.\"ID de producto\"\n",
    "\n",
    "    GROUP BY dp.\"Nombre de producto\"\n",
    "\n",
    ")\n",
    "\n",
    "SELECT\n",
    "    producto,\n",
    "    beneficio_total,\n",
    "    RANK() OVER(ORDER BY beneficio_total DESC) AS ranking\n",
    "\n",
    "FROM rentabilidad_producto\n",
    "\n",
    "ORDER BY ranking\n",
    "LIMIT 10;\n",
    "\"\"\"\n",
    "\n",
    "df = pd.read_sql(query1, engine)\n",
    "df"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "87e65953-c5cc-4e76-b9b9-ad37b05829fa",
   "metadata": {},
   "source": [
    "### 2. Window Function, ¿Qué categorías tienen mayores ventas pero menores márgenes?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "b0a4bf5b-bf56-4453-8ff0-26ed057e3f05",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Categoría</th>\n",
       "      <th>ventas_totales</th>\n",
       "      <th>beneficio_total</th>\n",
       "      <th>margen</th>\n",
       "      <th>promedio_ventas</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Tecnología</td>\n",
       "      <td>4.744557e+06</td>\n",
       "      <td>663778.73318</td>\n",
       "      <td>0.1399</td>\n",
       "      <td>4.214167e+06</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Mobiliario</td>\n",
       "      <td>4.110452e+06</td>\n",
       "      <td>285082.73020</td>\n",
       "      <td>0.0694</td>\n",
       "      <td>4.214167e+06</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Material de oficina</td>\n",
       "      <td>3.787493e+06</td>\n",
       "      <td>518595.82790</td>\n",
       "      <td>0.1369</td>\n",
       "      <td>4.214167e+06</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "             Categoría  ventas_totales  beneficio_total  margen  \\\n",
       "0           Tecnología    4.744557e+06     663778.73318  0.1399   \n",
       "1           Mobiliario    4.110452e+06     285082.73020  0.0694   \n",
       "2  Material de oficina    3.787493e+06     518595.82790  0.1369   \n",
       "\n",
       "   promedio_ventas  \n",
       "0     4.214167e+06  \n",
       "1     4.214167e+06  \n",
       "2     4.214167e+06  "
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "query2 = \"\"\"\n",
    "SELECT\n",
    "\n",
    "    dp.\"Categoría\",\n",
    "\n",
    "    SUM(fv.\"Ventas\") AS ventas_totales,\n",
    "\n",
    "    SUM(fv.\"Beneficio\") AS beneficio_total,\n",
    "\n",
    "    ROUND(\n",
    "        (\n",
    "            SUM(fv.\"Beneficio\") /\n",
    "            NULLIF(SUM(fv.\"Ventas\"),0)\n",
    "        )::numeric,\n",
    "        4\n",
    "    ) AS margen,\n",
    "\n",
    "    AVG(SUM(fv.\"Ventas\")) OVER() AS promedio_ventas\n",
    "\n",
    "FROM ecomerce_dwh.fact_ventas fv\n",
    "\n",
    "JOIN ecomerce_dwh.dim_producto dp\n",
    "ON fv.\"ID de producto\" = dp.\"ID de producto\"\n",
    "\n",
    "GROUP BY dp.\"Categoría\"\n",
    "\n",
    "ORDER BY ventas_totales DESC;\n",
    "\"\"\"\n",
    "\n",
    "df = pd.read_sql(query2, engine)\n",
    "df"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "dad3413a-8f5c-4cb7-a4ee-050465f33c90",
   "metadata": {},
   "source": [
    "### 3. COUNT FILTER, ¿Cómo impactan los descuentos en el beneficio final?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "f3aa2a81-1209-4fe5-9199-f50744493bb3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>pedidos_sin_descuento</th>\n",
       "      <th>pedidos_con_descuento</th>\n",
       "      <th>beneficio_promedio_sin_descuento</th>\n",
       "      <th>beneficio_promedio_con_descuento</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>29009</td>\n",
       "      <td>22281</td>\n",
       "      <td>61.039514</td>\n",
       "      <td>-13.609711</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   pedidos_sin_descuento  pedidos_con_descuento  \\\n",
       "0                  29009                  22281   \n",
       "\n",
       "   beneficio_promedio_sin_descuento  beneficio_promedio_con_descuento  \n",
       "0                         61.039514                        -13.609711  "
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "query3 = \"\"\"\n",
    "SELECT\n",
    "\n",
    "    COUNT(*) FILTER (\n",
    "        WHERE \"Descuento\" = 0\n",
    "    ) AS pedidos_sin_descuento,\n",
    "\n",
    "    COUNT(*) FILTER (\n",
    "        WHERE \"Descuento\" > 0\n",
    "    ) AS pedidos_con_descuento,\n",
    "\n",
    "    AVG(\"Beneficio\") FILTER (\n",
    "        WHERE \"Descuento\" = 0\n",
    "    ) AS beneficio_promedio_sin_descuento,\n",
    "\n",
    "    AVG(\"Beneficio\") FILTER (\n",
    "        WHERE \"Descuento\" > 0\n",
    "    ) AS beneficio_promedio_con_descuento\n",
    "\n",
    "FROM ecomerce_dwh.fact_ventas;\n",
    "\"\"\"\n",
    "\n",
    "df = pd.read_sql(query3, engine)\n",
    "df"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cc41300d-613f-4611-a459-1dbbd0ebc1a0",
   "metadata": {},
   "source": [
    "### 4. PERCENTILE_CONT, ¿Qué regiones presentan mejor desempeño comercial?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "f716f27b-0404-4fc0-b28c-68089b0f9222",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Región</th>\n",
       "      <th>ventas_totales</th>\n",
       "      <th>beneficio_total</th>\n",
       "      <th>mediana_beneficio</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Europa Occidental</td>\n",
       "      <td>1.731930e+06</td>\n",
       "      <td>218433.50850</td>\n",
       "      <td>15.3990</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Asia Oriental</td>\n",
       "      <td>8.550594e+05</td>\n",
       "      <td>167101.85100</td>\n",
       "      <td>23.7000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Asia Meridional</td>\n",
       "      <td>8.665727e+05</td>\n",
       "      <td>159336.42700</td>\n",
       "      <td>19.3800</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Centroamérica</td>\n",
       "      <td>1.223101e+06</td>\n",
       "      <td>158981.64816</td>\n",
       "      <td>9.2800</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Oceanía</td>\n",
       "      <td>1.100185e+06</td>\n",
       "      <td>120089.11200</td>\n",
       "      <td>8.7660</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Oeste de EE. UU.</td>\n",
       "      <td>7.254578e+05</td>\n",
       "      <td>108418.44890</td>\n",
       "      <td>11.1664</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Este de EE. UU.</td>\n",
       "      <td>6.787812e+05</td>\n",
       "      <td>91522.78000</td>\n",
       "      <td>8.1717</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Europa Septentrional</td>\n",
       "      <td>6.367792e+05</td>\n",
       "      <td>83923.91700</td>\n",
       "      <td>11.0835</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>Europa Oriental</td>\n",
       "      <td>3.100334e+05</td>\n",
       "      <td>77084.88000</td>\n",
       "      <td>14.3100</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>Europa Meridional</td>\n",
       "      <td>6.085940e+05</td>\n",
       "      <td>70109.41800</td>\n",
       "      <td>13.6500</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>África Septentrional</td>\n",
       "      <td>2.332166e+05</td>\n",
       "      <td>57836.25000</td>\n",
       "      <td>13.2900</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>Sur de EE. UU.</td>\n",
       "      <td>3.917219e+05</td>\n",
       "      <td>46749.43030</td>\n",
       "      <td>9.0720</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>Centro de EE. UU.</td>\n",
       "      <td>5.012399e+05</td>\n",
       "      <td>39706.36250</td>\n",
       "      <td>5.1840</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>África Central</td>\n",
       "      <td>1.436300e+05</td>\n",
       "      <td>35383.71000</td>\n",
       "      <td>13.9200</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>Caribe</td>\n",
       "      <td>3.242809e+05</td>\n",
       "      <td>34571.32104</td>\n",
       "      <td>7.1640</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>Sudamérica</td>\n",
       "      <td>6.172237e+05</td>\n",
       "      <td>28090.51788</td>\n",
       "      <td>5.9200</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>África Meridional</td>\n",
       "      <td>1.051918e+05</td>\n",
       "      <td>24158.55000</td>\n",
       "      <td>14.4750</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>África Oriental</td>\n",
       "      <td>1.278560e+05</td>\n",
       "      <td>21900.90900</td>\n",
       "      <td>8.7150</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>Asia Sudoriental</td>\n",
       "      <td>8.844232e+05</td>\n",
       "      <td>17852.32900</td>\n",
       "      <td>-1.3533</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>Canadá</td>\n",
       "      <td>6.692817e+04</td>\n",
       "      <td>17817.39000</td>\n",
       "      <td>12.3450</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>Asia Central</td>\n",
       "      <td>1.931146e+04</td>\n",
       "      <td>-7282.01100</td>\n",
       "      <td>-7.6140</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>África Occidental</td>\n",
       "      <td>1.738788e+05</td>\n",
       "      <td>-50407.78800</td>\n",
       "      <td>-8.6115</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>Asia Occidental</td>\n",
       "      <td>3.171070e+05</td>\n",
       "      <td>-53921.67000</td>\n",
       "      <td>-5.2620</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                  Región  ventas_totales  beneficio_total  mediana_beneficio\n",
       "0      Europa Occidental    1.731930e+06     218433.50850            15.3990\n",
       "1          Asia Oriental    8.550594e+05     167101.85100            23.7000\n",
       "2        Asia Meridional    8.665727e+05     159336.42700            19.3800\n",
       "3          Centroamérica    1.223101e+06     158981.64816             9.2800\n",
       "4                Oceanía    1.100185e+06     120089.11200             8.7660\n",
       "5       Oeste de EE. UU.    7.254578e+05     108418.44890            11.1664\n",
       "6        Este de EE. UU.    6.787812e+05      91522.78000             8.1717\n",
       "7   Europa Septentrional    6.367792e+05      83923.91700            11.0835\n",
       "8        Europa Oriental    3.100334e+05      77084.88000            14.3100\n",
       "9      Europa Meridional    6.085940e+05      70109.41800            13.6500\n",
       "10  África Septentrional    2.332166e+05      57836.25000            13.2900\n",
       "11        Sur de EE. UU.    3.917219e+05      46749.43030             9.0720\n",
       "12     Centro de EE. UU.    5.012399e+05      39706.36250             5.1840\n",
       "13        África Central    1.436300e+05      35383.71000            13.9200\n",
       "14                Caribe    3.242809e+05      34571.32104             7.1640\n",
       "15            Sudamérica    6.172237e+05      28090.51788             5.9200\n",
       "16     África Meridional    1.051918e+05      24158.55000            14.4750\n",
       "17       África Oriental    1.278560e+05      21900.90900             8.7150\n",
       "18      Asia Sudoriental    8.844232e+05      17852.32900            -1.3533\n",
       "19                Canadá    6.692817e+04      17817.39000            12.3450\n",
       "20          Asia Central    1.931146e+04      -7282.01100            -7.6140\n",
       "21     África Occidental    1.738788e+05     -50407.78800            -8.6115\n",
       "22       Asia Occidental    3.171070e+05     -53921.67000            -5.2620"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "query4 = \"\"\"\n",
    "SELECT\n",
    "\n",
    "    dg.\"Región\",\n",
    "\n",
    "    SUM(fv.\"Ventas\") AS ventas_totales,\n",
    "\n",
    "    SUM(fv.\"Beneficio\") AS beneficio_total,\n",
    "\n",
    "    PERCENTILE_CONT(0.5)\n",
    "    WITHIN GROUP (\n",
    "        ORDER BY fv.\"Beneficio\"\n",
    "    ) AS mediana_beneficio\n",
    "\n",
    "FROM ecomerce_dwh.fact_ventas fv\n",
    "\n",
    "JOIN ecomerce_dwh.dim_geografia dg\n",
    "ON fv.id_geografia = dg.id_geografia\n",
    "\n",
    "GROUP BY dg.\"Región\"\n",
    "\n",
    "ORDER BY beneficio_total DESC;\n",
    "\"\"\"\n",
    "\n",
    "df = pd.read_sql(query4, engine)\n",
    "df"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ec321afb-3a9d-44be-9ea3-1247f5635c67",
   "metadata": {},
   "source": [
    "### 5. CTE + LAG(), ¿Qué modos de envío generan mayores costos logísticos?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "053b929e-18c3-4955-9e87-af213d23dde6",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>anio</th>\n",
       "      <th>mes</th>\n",
       "      <th>modo_envio</th>\n",
       "      <th>costo_total</th>\n",
       "      <th>costo_mes_anterior</th>\n",
       "      <th>variacion_mensual</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2012</td>\n",
       "      <td>1</td>\n",
       "      <td>Clase estándar</td>\n",
       "      <td>5309.8480</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2012</td>\n",
       "      <td>2</td>\n",
       "      <td>Clase estándar</td>\n",
       "      <td>4921.2950</td>\n",
       "      <td>5309.8480</td>\n",
       "      <td>-388.5530</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2012</td>\n",
       "      <td>3</td>\n",
       "      <td>Clase estándar</td>\n",
       "      <td>5945.5055</td>\n",
       "      <td>4921.2950</td>\n",
       "      <td>1024.2105</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2012</td>\n",
       "      <td>4</td>\n",
       "      <td>Clase estándar</td>\n",
       "      <td>5504.4980</td>\n",
       "      <td>5945.5055</td>\n",
       "      <td>-441.0075</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2012</td>\n",
       "      <td>5</td>\n",
       "      <td>Clase estándar</td>\n",
       "      <td>7926.0150</td>\n",
       "      <td>5504.4980</td>\n",
       "      <td>2421.5170</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>187</th>\n",
       "      <td>2015</td>\n",
       "      <td>8</td>\n",
       "      <td>Urgente</td>\n",
       "      <td>9474.2140</td>\n",
       "      <td>6334.5320</td>\n",
       "      <td>3139.6820</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>188</th>\n",
       "      <td>2015</td>\n",
       "      <td>9</td>\n",
       "      <td>Urgente</td>\n",
       "      <td>13263.0330</td>\n",
       "      <td>9474.2140</td>\n",
       "      <td>3788.8190</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>189</th>\n",
       "      <td>2015</td>\n",
       "      <td>10</td>\n",
       "      <td>Urgente</td>\n",
       "      <td>10959.7640</td>\n",
       "      <td>13263.0330</td>\n",
       "      <td>-2303.2690</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>190</th>\n",
       "      <td>2015</td>\n",
       "      <td>11</td>\n",
       "      <td>Urgente</td>\n",
       "      <td>12692.3570</td>\n",
       "      <td>10959.7640</td>\n",
       "      <td>1732.5930</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>191</th>\n",
       "      <td>2015</td>\n",
       "      <td>12</td>\n",
       "      <td>Urgente</td>\n",
       "      <td>13453.6110</td>\n",
       "      <td>12692.3570</td>\n",
       "      <td>761.2540</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>192 rows × 6 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     anio  mes      modo_envio  costo_total  costo_mes_anterior  \\\n",
       "0    2012    1  Clase estándar    5309.8480                 NaN   \n",
       "1    2012    2  Clase estándar    4921.2950           5309.8480   \n",
       "2    2012    3  Clase estándar    5945.5055           4921.2950   \n",
       "3    2012    4  Clase estándar    5504.4980           5945.5055   \n",
       "4    2012    5  Clase estándar    7926.0150           5504.4980   \n",
       "..    ...  ...             ...          ...                 ...   \n",
       "187  2015    8         Urgente    9474.2140           6334.5320   \n",
       "188  2015    9         Urgente   13263.0330           9474.2140   \n",
       "189  2015   10         Urgente   10959.7640          13263.0330   \n",
       "190  2015   11         Urgente   12692.3570          10959.7640   \n",
       "191  2015   12         Urgente   13453.6110          12692.3570   \n",
       "\n",
       "     variacion_mensual  \n",
       "0                  NaN  \n",
       "1            -388.5530  \n",
       "2            1024.2105  \n",
       "3            -441.0075  \n",
       "4            2421.5170  \n",
       "..                 ...  \n",
       "187          3139.6820  \n",
       "188          3788.8190  \n",
       "189         -2303.2690  \n",
       "190          1732.5930  \n",
       "191           761.2540  \n",
       "\n",
       "[192 rows x 6 columns]"
      ]
     },
     "execution_count": 23,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "query5 = \"\"\"\n",
    "WITH costos_envio AS (\n",
    "\n",
    "    SELECT\n",
    "\n",
    "        dt.anio,\n",
    "        dt.mes,\n",
    "        de.\"Modo de envío\" AS modo_envio,\n",
    "\n",
    "        SUM(fv.\"Costo de envío\") AS costo_total\n",
    "\n",
    "    FROM ecomerce_dwh.fact_ventas fv\n",
    "\n",
    "    JOIN ecomerce_dwh.dim_envio de\n",
    "        ON fv.id_envio = de.id_envio\n",
    "\n",
    "    JOIN ecomerce_dwh.dim_tiempo dt\n",
    "        ON fv.id_tiempo = dt.id_tiempo\n",
    "\n",
    "    GROUP BY\n",
    "        dt.anio,\n",
    "        dt.mes,\n",
    "        de.\"Modo de envío\"\n",
    "\n",
    ")\n",
    "\n",
    "SELECT\n",
    "\n",
    "    anio,\n",
    "    mes,\n",
    "    modo_envio,\n",
    "    costo_total,\n",
    "\n",
    "    LAG(costo_total) OVER (\n",
    "        PARTITION BY modo_envio\n",
    "        ORDER BY anio, mes\n",
    "    ) AS costo_mes_anterior,\n",
    "\n",
    "    costo_total -\n",
    "    LAG(costo_total) OVER (\n",
    "        PARTITION BY modo_envio\n",
    "        ORDER BY anio, mes\n",
    "    ) AS variacion_mensual\n",
    "\n",
    "FROM costos_envio\n",
    "\n",
    "ORDER BY\n",
    "    modo_envio,\n",
    "    anio,\n",
    "    mes;\n",
    "\"\"\"\n",
    "\n",
    "df = pd.read_sql(query5, engine)\n",
    "df"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
